let suggestionsArray=[
    "Madrid, España",
    "Rabat, Marruecos",
    "París, Francia",
    "Pekin, China",
    "Oslo, Noruega",
    "Reikiabik, Islandia",
    "Viena, Austria",
    "Helsinki, Finlandia",
    "Kiev, Ucrania",
    "Bucarest, Rumania",
    "Budapest, Hungría",
    "Bruselas, Bélgica",
    "Berlín, Alemania",
    "Atenas, Grecia",
    "Estocolmo, Suecia",
    "Belgrado, Serbia",
    "Londres, Reino Unido",
    "Ámsterdam, Holanda",
    "Roma, Italia",
    "Minsk, Bielorrusia",
    "Varsovia, Polonia",
    "Dublín, Irlanda",
    "Zagreb, Croacia",
    "Wellington, Nueva Zelanda",
    "Ottawa, Canadá",
    "Viena, Austria",
    "Berna, Suiza",
    "Edimburgo, Escocia",
    "Sydney, Australia",
    "Lisboa, Portugal",
    "Podgorica, Montenegro",
    "Liubliana, Eslovenia"
];